<a href="https://colab.research.google.com/github/swirita/Chicago-Crime-Analysis-and-Forecasting/blob/main/notebooks/01_prepare_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prepare Chicago Crime Data for GitHub Repository
- Author: Siwar Ehwass
- Original Notebook Source: https://github.com/coding-dojo-data-science/preparing-chicago-crime-data
- Updated 09/03/26

> - This notebook will process a "Crimes - 2001 to Present.csv" crime file in your Downloads folder and save it as smaller .csv's in a new "Data/Chicago/" folder inside this notebook's folder/repo.

## **INSTRUCTIONS**
- 1. Go to the Chicago Data Portal's page for [Crimes - 2001 to Preset](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2/about_data).
- 2. Click on the Export button on the top right and select CSV.
  - Save the file to your Downloads folder instead of your repository. **The file is too big for a repository**.

- 3. Wait for the full file to download.
  - It is very large (over >1.7GB and may take several minutes to fully download.)

- 4. Once the download is complete, change RAW_FILE variable below to match the filepath to the downloaded file.

In [16]:
import pandas as pd
import os

In [12]:
fpath="/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/Crimes_-_2001_to_Present_20260903.csv"
df = pd.read_csv(fpath)
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14311314,JK388005,08/25/2026 12:00:00 AM,001XX N ADA ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,27.0,28.0,14,NaN,NaN,2026,09/01/2026 03:46:12 PM,NaN,NaN,NaN
1,14304337,JK386333,08/25/2026 12:00:00 AM,086XX S COTTAGE GROVE AVE,0630,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESTAURANT,False,False,...,8.0,44.0,05,1183072.0,1847849.0,2026,09/01/2026 03:46:12 PM,41.737696,-87.604853,"(41.737695862, -87.604852868)"
2,14305954,JK388729,08/25/2026 12:00:00 AM,0000X S PULASKI RD,0710,THEFT,THEFT FROM MOTOR VEHICLE,RESTAURANT,False,False,...,28.0,26.0,06,1149731.0,1899625.0,2026,09/01/2026 03:46:12 PM,41.880486,-87.725665,"(41.880486258, -87.725665179)"
3,14304479,JK386610,08/25/2026 12:00:00 AM,045XX N BROADWAY,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,False,False,...,46.0,3.0,06,1168276.0,1930258.0,2026,09/01/2026 03:46:12 PM,41.964164,-87.656682,"(41.96416436, -87.656682274)"
4,14304654,JK386849,08/25/2026 12:00:00 AM,012XX N CLYBOURN AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,27.0,8.0,26,1172799.0,1908580.0,2026,09/01/2026 03:46:12 PM,41.904580,-87.640697,"(41.904579871, -87.640696598)"

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8627693 entries, 0 to 8627692
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.3+ GB

In [17]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

## Full Workflow

In [18]:
chicago_full = df #pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14311314,JK388005,08/25/2026 12:00:00 AM,001XX N ADA ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,27.0,28.0,14,NaN,NaN,2026,09/01/2026 03:46:12 PM,NaN,NaN,NaN
1,14304337,JK386333,08/25/2026 12:00:00 AM,086XX S COTTAGE GROVE AVE,0630,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESTAURANT,False,False,...,8.0,44.0,05,1183072.0,1847849.0,2026,09/01/2026 03:46:12 PM,41.737696,-87.604853,"(41.737695862, -87.604852868)"
2,14305954,JK388729,08/25/2026 12:00:00 AM,0000X S PULASKI RD,0710,THEFT,THEFT FROM MOTOR VEHICLE,RESTAURANT,False,False,...,28.0,26.0,06,1149731.0,1899625.0,2026,09/01/2026 03:46:12 PM,41.880486,-87.725665,"(41.880486258, -87.725665179)"
3,14304479,JK386610,08/25/2026 12:00:00 AM,045XX N BROADWAY,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,False,False,...,46.0,3.0,06,1168276.0,1930258.0,2026,09/01/2026 03:46:12 PM,41.964164,-87.656682,"(41.96416436, -87.656682274)"
4,14304654,JK386849,08/25/2026 12:00:00 AM,012XX N CLYBOURN AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,27.0,8.0,26,1172799.0,1908580.0,2026,09/01/2026 03:46:12 PM,41.904580,-87.640697,"(41.904579871, -87.640696598)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8627688,7548864,HS352185,01/01/2001 12:00:00 AM,016XX N KILDARE AVE,0842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,...,30.0,23.0,06,1147512.0,1910556.0,2001,06/15/2010 01:13:49 AM,41.910525,-87.733533,"(41.910524926, -87.733532609)"
8627689,7829546,HS637646,01/01/2001 12:00:00 AM,031XX W FULTON BLVD,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,27.0,27.0,06,1155098.0,1901789.0,2001,12/16/2010 12:38:11 AM,41.886319,-87.705900,"(41.88631852, -87.705899872)"
8627690,8146039,HT380969,01/01/2001 12:00:00 AM,047XX W MONTANA ST,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,True,...,31.0,19.0,02,1144295.0,1915861.0,2001,09/07/2021 03:41:02 PM,41.925144,-87.745217,"(41.925143516, -87.745217143)"
8627691,8175138,HT409754,01/01/2001 12:00:00 AM,111XX S ESMOND ST,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,...,19.0,75.0,17,1165662.0,1830520.0,2001,09/23/2025 03:41:47 PM,41.690529,-87.669128,"(41.690529005, -87.669128253)"
8627692,8197725,HT431595,01/01/2001 12:00:00 AM,009XX N HOMAN AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,True,...,27.0,23.0,02,1153583.0,1905844.0,2001,09/20/2011 12:43:48 AM,41.897476,-87.711355,"(41.8974761, -87.711355397)"

In [19]:
# this cell can take up to 1 min to run
date_format = "%m/%d/%Y %I:%M:%S %p"

chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Datetime
8627266,5462733,HN290220,01/01/2001 01:00:00 AM,058XX S INDIANA AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,...,40.0,17,1178551.0,1866538.0,2001,09/23/2025 03:41:47 PM,41.789084,-87.620849,"(41.789084341, -87.620849345)",2001-01-01 01:00:00
8627250,1311933,G002620,01/01/2001 01:00:00 AM,016XX N LEAVITT ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,...,NaN,17,1161480.0,1910757.0,2001,08/17/2015 03:03:40 PM,41.910797,-87.682214,"(41.910796986, -87.682213687)",2001-01-01 01:00:00
8627251,1312658,G004147,01/01/2001 01:00:00 AM,040XX W CORTLAND ST,0460,BATTERY,SIMPLE,STREET,False,False,...,NaN,08B,1149393.0,1912364.0,2001,08/17/2015 03:03:40 PM,41.915450,-87.726575,"(41.915449949, -87.726575474)",2001-01-01 01:00:00
8627252,1313213,G001554,01/01/2001 01:00:00 AM,071XX S LAFAYETTE AV,0460,BATTERY,SIMPLE,VEHICLE NON-COMMERCIAL,False,True,...,NaN,08B,1177027.0,1857893.0,2001,08/17/2015 03:03:40 PM,41.765396,-87.626698,"(41.765396066, -87.626697771)",2001-01-01 01:00:00
8627253,1315458,G005079,01/01/2001 01:00:00 AM,016XX N HUMBOLDT BL,0820,THEFT,$500 AND UNDER,STREET,False,False,...,NaN,06,1156090.0,1910543.0,2001,08/17/2015 03:03:40 PM,41.910320,-87.702020,"(41.910320325, -87.702020443)",2001-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,14304654,JK386849,08/25/2026 12:00:00 AM,012XX N CLYBOURN AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,8.0,26,1172799.0,1908580.0,2026,09/01/2026 03:46:12 PM,41.904580,-87.640697,"(41.904579871, -87.640696598)",2026-08-25 12:00:00
3,14304479,JK386610,08/25/2026 12:00:00 AM,045XX N BROADWAY,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,False,False,...,3.0,06,1168276.0,1930258.0,2026,09/01/2026 03:46:12 PM,41.964164,-87.656682,"(41.96416436, -87.656682274)",2026-08-25 12:00:00
2,14305954,JK388729,08/25/2026 12:00:00 AM,0000X S PULASKI RD,0710,THEFT,THEFT FROM MOTOR VEHICLE,RESTAURANT,False,False,...,26.0,06,1149731.0,1899625.0,2026,09/01/2026 03:46:12 PM,41.880486,-87.725665,"(41.880486258, -87.725665179)",2026-08-25 12:00:00
1,14304337,JK386333,08/25/2026 12:00:00 AM,086XX S COTTAGE GROVE AVE,0630,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESTAURANT,False,False,...,44.0,05,1183072.0,1847849.0,2026,09/01/2026 03:46:12 PM,41.737696,-87.604853,"(41.737695862, -87.604852868)",2026-08-25 12:00:00
0,14311314,JK388005,08/25/2026 12:00:00 AM,001XX N ADA ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,28.0,14,NaN,NaN,2026,09/01/2026 03:46:12 PM,NaN,NaN,NaN,2026-08-25 12:00:00

### Separate the Full Dataset by Years

In [20]:
chicago_full['Datetime'].dt.year

8627266    2001
8627250    2001
8627251    2001
8627252    2001
8627253    2001
           ...
4          2026
3          2026
2          2026
1          2026
0          2026
Name: Datetime, Length: 8627693, dtype: int32

In [21]:
# Removing 2027
filter_pre_2027 =  chicago_full['Datetime'].dt.year<2027
chicago_2027 = chicago_full[~filter_pre_2027]
chicago_full = chicago_full[filter_pre_2027]
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Datetime
8627266,5462733,HN290220,01/01/2001 01:00:00 AM,058XX S INDIANA AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,...,40.0,17,1178551.0,1866538.0,2001,09/23/2025 03:41:47 PM,41.789084,-87.620849,"(41.789084341, -87.620849345)",2001-01-01 01:00:00
8627250,1311933,G002620,01/01/2001 01:00:00 AM,016XX N LEAVITT ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,...,NaN,17,1161480.0,1910757.0,2001,08/17/2015 03:03:40 PM,41.910797,-87.682214,"(41.910796986, -87.682213687)",2001-01-01 01:00:00
8627251,1312658,G004147,01/01/2001 01:00:00 AM,040XX W CORTLAND ST,0460,BATTERY,SIMPLE,STREET,False,False,...,NaN,08B,1149393.0,1912364.0,2001,08/17/2015 03:03:40 PM,41.915450,-87.726575,"(41.915449949, -87.726575474)",2001-01-01 01:00:00
8627252,1313213,G001554,01/01/2001 01:00:00 AM,071XX S LAFAYETTE AV,0460,BATTERY,SIMPLE,VEHICLE NON-COMMERCIAL,False,True,...,NaN,08B,1177027.0,1857893.0,2001,08/17/2015 03:03:40 PM,41.765396,-87.626698,"(41.765396066, -87.626697771)",2001-01-01 01:00:00
8627253,1315458,G005079,01/01/2001 01:00:00 AM,016XX N HUMBOLDT BL,0820,THEFT,$500 AND UNDER,STREET,False,False,...,NaN,06,1156090.0,1910543.0,2001,08/17/2015 03:03:40 PM,41.910320,-87.702020,"(41.910320325, -87.702020443)",2001-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,14304654,JK386849,08/25/2026 12:00:00 AM,012XX N CLYBOURN AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,8.0,26,1172799.0,1908580.0,2026,09/01/2026 03:46:12 PM,41.904580,-87.640697,"(41.904579871, -87.640696598)",2026-08-25 12:00:00
3,14304479,JK386610,08/25/2026 12:00:00 AM,045XX N BROADWAY,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,False,False,...,3.0,06,1168276.0,1930258.0,2026,09/01/2026 03:46:12 PM,41.964164,-87.656682,"(41.96416436, -87.656682274)",2026-08-25 12:00:00
2,14305954,JK388729,08/25/2026 12:00:00 AM,0000X S PULASKI RD,0710,THEFT,THEFT FROM MOTOR VEHICLE,RESTAURANT,False,False,...,26.0,06,1149731.0,1899625.0,2026,09/01/2026 03:46:12 PM,41.880486,-87.725665,"(41.880486258, -87.725665179)",2026-08-25 12:00:00
1,14304337,JK386333,08/25/2026 12:00:00 AM,086XX S COTTAGE GROVE AVE,0630,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESTAURANT,False,False,...,44.0,05,1183072.0,1847849.0,2026,09/01/2026 03:46:12 PM,41.737696,-87.604853,"(41.737695862, -87.604852868)",2026-08-25 12:00:00
0,14311314,JK388005,08/25/2026 12:00:00 AM,001XX N ADA ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,28.0,14,NaN,NaN,2026,09/01/2026 03:46:12 PM,NaN,NaN,NaN,2026-08-25 12:00:00

In [36]:
# save the years for every crime
chicago_full["Year"] = chicago_full['Datetime'].dt.year.astype(str)
chicago_full["Year"].value_counts().sort_index()

Year
2001    485974
2002    486839
2003    476007
2004    469443
2005    453795
2006    448205
2007    437111
2008    427225
2009    392871
2010    370572
2011    352064
2012    336391
2013    307631
2014    275888
2015    264909
2016    269999
2017    269323
2018    269189
2019    261742
2020    212793
2021    209747
2022    240156
2023    263449
2024    259267
2025    237695
2026    149408
Name: count, dtype: int64

In [23]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [24]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols)
chicago_final = chicago_final.set_index('Datetime')
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,5462733,01/01/2001 01:00:00 AM,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,233,2.0,20.0,2001,41.789084,-87.620849
2001-01-01 01:00:00,1311933,01/01/2001 01:00:00 AM,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,1434,14.0,NaN,2001,41.910797,-87.682214
2001-01-01 01:00:00,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.0,NaN,2001,41.915450,-87.726575
2001-01-01 01:00:00,1313213,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,VEHICLE NON-COMMERCIAL,False,True,731,7.0,NaN,2001,41.765396,-87.626698
2001-01-01 01:00:00,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.0,NaN,2001,41.910320,-87.702020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-25 12:00:00,14304654,08/25/2026 12:00:00 AM,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,1821,18.0,27.0,2026,41.904580,-87.640697
2026-08-25 12:00:00,14304479,08/25/2026 12:00:00 AM,THEFT,RETAIL THEFT,GROCERY FOOD STORE,False,False,1913,19.0,46.0,2026,41.964164,-87.656682
2026-08-25 12:00:00,14305954,08/25/2026 12:00:00 AM,THEFT,THEFT FROM MOTOR VEHICLE,RESTAURANT,False,False,1115,11.0,28.0,2026,41.880486,-87.725665
2026-08-25 12:00:00,14304337,08/25/2026 12:00:00 AM,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESTAURANT,False,False,632,6.0,8.0,2026,41.737696,-87.604853
2026-08-25 12:00:00,14311314,08/25/2026 12:00:00 AM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1224,12.0,27.0,2026,NaN,NaN

In [25]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024',
       '2025', '2026'], dtype=object)

In [26]:
FINAL_DROP = ['Year']

### Set the Google Drive Save Location

In [37]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
import os
import glob

PROJECT_FOLDER = (
    "/content/drive/MyDrive/"
    "Chicago-Crime-Analysis-and-Forecasting"
)

OUTPUT_FOLDER = os.path.join(
    PROJECT_FOLDER,
    "data",
    "raw"
)

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

print("Saving yearly files to:", OUTPUT_FOLDER)

Saving yearly files to: /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw

In [39]:
print(f"[i] Saving CSV files to {OUTPUT_FOLDER}")

for year in year_bins:

    # Select one year
    temp_df = chicago_final.loc[year].copy()

    # Sort by datetime
    temp_df = temp_df.sort_index()

    # Remove Datetime index and Year column
    temp_df = temp_df.reset_index(drop=True)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # Create the output filename
    fname_temp = os.path.join(
        OUTPUT_FOLDER,
        f"Chicago-Crime_{year}.csv"
    )

    # Save the yearly CSV
    temp_df.to_csv(fname_temp, index=False)

    print(f"- Successfully saved {fname_temp}")

[i] Saving CSV files to /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2001.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2002.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2003.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2004.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2005.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2006.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2007.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2008.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2009.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2010.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2011.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2012.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2013.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2014.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2015.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2016.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2017.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2018.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2019.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2020.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2021.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2022.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2023.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2024.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2025.csv
- Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2026.csv

In [40]:
saved_files = sorted(
    glob.glob(
        os.path.join(
            OUTPUT_FOLDER,
            "Chicago-Crime_*.csv"
        )
    )
)

print(f"{len(saved_files)} yearly CSV files were found.")

saved_files

26 yearly CSV files were found.

['/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2001.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2002.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2003.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2004.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2005.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2006.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2007.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2008.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2009.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2010.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2011.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2012.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2013.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2014.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2015.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2016.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2017.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2018.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2019.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2020.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2021.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2022.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2023.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2024.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2025.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2026.csv']

In [41]:
readme = """# Chicago Crime Data

Source:
https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2

Preparation:
- Downloaded on September 3, 2026.
- Filtered to include records before January 1, 2027.
- Includes available crime records from 2001 through September 3, 2026.
- The 2026 data represents a partial year.
- Files are split into one CSV file per year.
- The full source CSV is too large for GitHub.

Example usage:

    import glob
    import pandas as pd

    folder = "data/raw/"
    crime_files = sorted(
        glob.glob(folder + "Chicago-Crime_*.csv")
    )

    df = pd.concat(
        [pd.read_csv(file) for file in crime_files],
        ignore_index=True
    )
"""

print(readme)

# Chicago Crime Data

Source:
https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2

Preparation:
- Downloaded on September 3, 2026.
- Filtered to include records before January 1, 2027.
- Includes available crime records from 2001 through September 3, 2026.
- The 2026 data represents a partial year.
- Files are split into one CSV file per year.
- The full source CSV is too large for GitHub.

Example usage:

    import glob
    import pandas as pd

    folder = "data/raw/"
    crime_files = sorted(
        glob.glob(folder + "Chicago-Crime_*.csv")
    )

    df = pd.concat(
        [pd.read_csv(file) for file in crime_files],
        ignore_index=True
    )

In [42]:
readme_fpath = os.path.join(
    OUTPUT_FOLDER,
    "README.txt"
)

with open(readme_fpath, "w", encoding="utf-8") as file:
    file.write(readme)

print(f"Successfully saved {readme_fpath}")

Successfully saved /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/README.txt

### Making a Zip File

In [43]:
files_to_zip = saved_files + [readme_fpath]

files_to_zip

['/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2001.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2002.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2003.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2004.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2005.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2006.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2007.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2008.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2009.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2010.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2011.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2012.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2013.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2014.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2015.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2016.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2017.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2018.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2019.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2020.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2021.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2022.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2023.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2024.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2025.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/Chicago-Crime_2026.csv',
 '/content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/raw/README.txt']

In [44]:
import zipfile

ZIP_FILE = os.path.join(
    PROJECT_FOLDER,
    "data",
    "Chicago_Crime_2001-2026.zip"
)

with zipfile.ZipFile(
    ZIP_FILE,
    mode="w",
    compression=zipfile.ZIP_DEFLATED,
    compresslevel=9
) as zip_file:

    for file in files_to_zip:
        zip_file.write(
            file,
            arcname="Data/" + os.path.basename(file)
        )

print(f"Successfully created: {ZIP_FILE}")

Successfully created: /content/drive/MyDrive/Chicago-Crime-Analysis-and-Forecasting/data/Chicago_Crime_2001-2026.zip

### Confirmation

In [45]:
# Get the list of yearly CSV files
crime_files = sorted(
    glob.glob(
        os.path.join(OUTPUT_FOLDER, "Chicago-Crime_*.csv")
    )
)

# Load only 5 rows from each file to verify them
sample_df = pd.concat(
    [pd.read_csv(file, nrows=5) for file in crime_files],
    ignore_index=True
)

sample_df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude
0,5462733,01/01/2001 01:00:00 AM,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,233,2.0,20.0,41.789084,-87.620849
1,1311933,01/01/2001 01:00:00 AM,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,1434,14.0,NaN,41.910797,-87.682214
2,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.0,NaN,41.915450,-87.726575
3,1313213,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,VEHICLE NON-COMMERCIAL,False,True,731,7.0,NaN,41.765396,-87.626698
4,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.0,NaN,41.910320,-87.702020
...,...,...,...,...,...,...,...,...,...,...,...,...
125,14137163,01/01/2026 01:00:00 AM,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,APARTMENT,False,False,2233,22.0,21.0,41.702172,-87.637834
126,14108079,01/01/2026 01:00:00 AM,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,412,4.0,8.0,41.734155,-87.586856
127,14102503,01/01/2026 01:00:00 AM,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,BAR OR TAVERN,False,False,1214,12.0,34.0,41.885698,-87.644981
128,14092910,01/01/2026 01:00:00 AM,THEFT,OVER $500,APARTMENT,False,False,614,6.0,17.0,41.744012,-87.663279
129,14075329,01/01/2026 01:00:00 AM,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,True,424,4.0,10.0,41.738451,-87.549049

In [46]:
years = pd.to_datetime(
    sample_df["Date"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors="coerce"
).dt.year

years.value_counts().sort_index()

Date
2001    5
2002    5
2003    5
2004    5
2005    5
2006    5
2007    5
2008    5
2009    5
2010    5
2011    5
2012    5
2013    5
2014    5
2015    5
2016    5
2017    5
2018    5
2019    5
2020    5
2021    5
2022    5
2023    5
2024    5
2025    5
2026    5
Name: count, dtype: int64